# Generated by Django 2.2.4 on 2019-08-29 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_ong'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ong',
            new_name='Ongs',
        ),
    ]
